food/urls.py
from . import views
from django.urls import path 

app_name = 'food'
urlpatterns = [
    path('',views.index,name='index'),
    path('<int:item_id>/',views.detail,name='detail'),
    path('item/',views.item,name='item'),
    # add item
    path('add',views.create_item,name='create_item'),
    path('update/<int:id/>',views.update_item,name='update_item'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls'))

]

food/models.py
from django.db import models

# Create your models here.

class Item(models.Model):


    def __str__(self):
        return self.item_name
        
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price=models.IntegerField()
    item_image = models.CharField(max_length=500,default="https://cdn.dribbble.com/users/1012566/screenshots/4187820/topic-2.jpg")

food/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = {'item_name','item_desc','item_price','item_image'}

food/views.py
from django.shortcuts import render,redirect 
from django.http import HttpResponse
from . models import Item 
from django.template import loader
from .forms import ItemForm

# Create your views here.

def index(request):
    item_list = Item.objects.all()

    context={
        'item_list':item_list,
        
    }
    return render(request,'food/index.html',context)

def item(request):
    return HttpResponse('<h1> This is an item view </h1>')


def detail(request,item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item':item,
    }
    return render(request,'food/detail.html',context)


def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')


    return render(request,'food/item-form.html', {'form':form})


def update_item(request,id):
    item=Item.objects.get(id=id)
    form = ItemForm(request.POST or None,instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request,'food/item-form.html',{'form':form,'item':item})

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-dark">FoodApp</a>

        <div class="navbar">
            <a class="nav-item nav-link" href="{% url 'food:create_item'%}"> Add Item </a>
            <a class="nav-item nav-link" href="#"> Delete Item </a>
            <a class="nav-item nav-link" href="#"> view Item </a>
        </div>    
    </nav>

    {% block body %}
    {% endblock %}
    
</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html'%}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img height="300px" src="{{ item.item_image }}" class="card" />
        </div>

    </div class="col-md-6">
    <h1> {{item.itme_name}} </h1>
    <h2> {{item.item_desc}} </h2>
    <h3> {{item.item_price}} </h3>

    </div>
    </div>
    </div>









    {% endblock %}

food/templates/food/index.html
{% extends 'food/base.html'%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

</head>

<body>

    {% block body %}

    {% for item in item_list %}

        <div class="row">
            <div class="col-md-3 offset-md-2"> 
                <img class="card" height="150px" src="{{ item.item_image }}"/>
            </div>
            <div class="col-md-4">
                <h3> {{ item.item_name }} </h3>
                <h5> {{ item.item_desc }}  </h5>
                <h6>$ {{ item.item_price }} </h6>
            
            </div>
            <div class="col-md-2">
        </div> 
        </div>
        <ul>
            <li>
                <a href="{%url 'food:detail' item.id %}">
                    {{item.id}} -- {{item.item_name}} </a>

            </li>

        </ul>
    {% endfor %}
    {% endblock %}


</body>

</html>

food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}

<for method="POST">
    {% csrf_token %}
    {{ form }}
    
    <button type="submit">Save</button>
</form>
{% endblock %}